name: Deploy to Vercel

on:
  push:
    branches:
      - Main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: team_wK9izCEMsjBjByHiskD6GOU4
          VERCEL_PROJECT_ID: prj_QnxAm1UFAaHdQqLbATlkgJ2zTweK
